
import { StickerItem } from './types';

export const INITIAL_ITEMS: StickerItem[] = [
    { id: 1, name: 'Artisan Brick', price: 76.98, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/ArtisanBrick.tgs', color: 'c1' },
    { id: 2, name: 'Astral Shard', price: 174.00, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/AstralShard.tgs', color: 'c2' },
    { id: 4, name: 'Bow Tie', price: 4.50, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/BowTie.tgs', color: 'c4' },
    { id: 5, name: 'Bunny Muffin', price: 5.80, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/BunnyMuffin.tgs', color: 'c5' },
    { id: 6, name: 'Clover Pin', price: 3.60, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/CloverPin.tgs', color: 'c6' },
    { id: 7, name: 'Crystal Ball', price: 9.75, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/CrystalBall.tgs', color: 'c1' },
    { id: 8, name: 'Cupid Charm', price: 18.00, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/CupidCharm.tgs', color: 'c2' },
    { id: 9, name: 'Desk Calendar', price: 2.94, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/DeskCalendar.tgs', color: 'c3' },
    { id: 10, name: 'Diamond Ring', price: 23.23, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/DiamondRing.tgs', color: 'c4' },
    { id: 11, name: "Durov's Cap", price: 769.00, tgs: "https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/Durov'sCap.tgs", color: 'c5' },
    { id: 12, name: 'Electric Skull', price: 30.33, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/ElectricSkull.tgs', color: 'c6' },
    { id: 13, name: 'Eternal Rose', price: 19.20, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/EternalRose.tgs', color: 'c1' },
    { id: 14, name: 'Evil Eye', price: 5.92, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/EvilEye.tgs', color: 'c2' },
    { id: 15, name: 'Faith Amulet', price: 3.49, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/FaithAmulet.tgs', color: 'c3' },
    { id: 16, name: 'Flying Broom', price: 9.50, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/FlyingBroom.tgs', color: 'c4' },
    { id: 17, name: 'Fresh Socks', price: 3.55, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/FreshSocks.tgs', color: 'c5' },
    { id: 18, name: 'Genie Lamp', price: 48.00, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/GenieLamp.tgs', color: 'c6' },
    { id: 19, name: 'Hanging Star', price: 7.12, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/HangingStar.tgs', color: 'c1' },
    { id: 20, name: 'Happy Brownie', price: 3.13, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/HappyBrownie.tgs', color: 'c2' },
    { id: 21, name: 'Heart Locket', price: 2079.99, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/HeartLocket.tgs', color: 'c3' },
    { id: 22, name: 'Heroic Helmet', price: 255, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/HeroicHelmet.tgs', color: 'c4' },
    { id: 23, name: 'Ice Cream', price: 2.97, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/IceCream.tgs', color: 'c5' },
    { id: 24, name: 'Ice Cream Cone', price: 3.10, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/IceCreamCone.tgs', color: 'c6' },
    { id: 25, name: 'Ice Cream Scoops', price: 4.15, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/IceCreamScoops.tgs', color: 'c1' },
    { id: 26, name: 'Instant Ramen', price: 2.98, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/InstantRamen.tgs', color: 'c2' },
    { id: 27, name: 'Ion Gem', price: 98.39, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/IonGem.tgs', color: 'c3' },
    { id: 28, name: 'Input Key', price: 4.15, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/InputKey.tgs', color: 'c3' },
    { id: 29, name: 'Kitty Medallion', price: 5.00, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/KittyMedallion.tgs', color: 'c4' },
    { id: 30, name: 'Light Sword', price: 5.00, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/LightSword.tgs', color: 'c5' },
    { id: 31, name: 'Ionic Dryer', price: 15.40, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/LonicDryer.tgs', color: 'c6' },
    { id: 32, name: 'Love Potion', price: 13.41, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/LovePotion.tgs', color: 'c1' },
    { id: 33, name: 'Magic Potion', price: 80.50, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/MagicPotion.tgs', color: 'c2' },
    { id: 34, name: 'Mighty Arm', price: 192.47, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/MightyArm.tgs', color: 'c3' },
    { id: 35, name: 'Mini Oscar', price: 96.32, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/MiniOscar.tgs', color: 'c4' },
    { id: 36, name: 'Money Pot', price: 3.79, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/MoneyPot.tgs', color: 'c5' },
    { id: 37, name: 'Moon Pendant', price: 4.37, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/MoonPendant.tgs', color: 'c6' },
    { id: 38, name: 'Nail Bracelet', price: 123.37, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/NailBracelet.tgs', color: 'c1' },
    { id: 39, name: 'Neko Helmet', price: 33.00, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/NekoHelmet.tgs', color: 'c2' },
    { id: 40, name: 'Perfume Bottle', price: 95.35, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/PerfemuBottle.tgs', color: 'c3' },
    { id: 41, name: 'Pet Snake', price: 3.09, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/PetSnake.tgs', color: 'c4' },
    { id: 54, name: 'Precious Peach', price: 393.99, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/PreciousPeach.tgs', color: 'c4' },
    { id: 42, name: 'Plush Pepe', price: 10088.00, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/PlushPepe.tgs', color: 'c5' },
    { id: 43, name: 'Sharp Tongue', price: 43.00, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/SharpTongue.tgs', color: 'c6' },
    { id: 44, name: 'Signet Ring', price: 29.98, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/SignetRing.tgs', color: 'c1' },
    { id: 45, name: 'Sky Stilettos', price: 9.99, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/SkyStilettos.tgs', color: 'c2' },
    { id: 46, name: 'Sleigh Bell', price: 2.96, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/SleighBell.tgs', color: 'c3' },
    { id: 47, name: 'Star Notepad', price: 3.80, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/StarNotepad.tgs', color: 'c4' },
    { id: 48, name: 'Swiss Watch', price: 44.15, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/SwissWatch.tgs', color: 'c5' },
    { id: 49, name: 'Tama Gadget', price: 3.36, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/TamaGadget.tgs', color: 'c6' },
    { id: 50, name: 'Toy Bear', price: 31.93, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/ToyBear.tgs', color: 'c6' },
    { id: 51, name: 'Top Hat', price: 9.79, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/TopHat.tgs', color: 'c1' },
    { id: 52, name: 'Vintage Cigar', price: 28.99, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/VintageSigar.tgs', color: 'c2' },
    { id: 53, name: 'Voodoo Doll', price: 25.60, tgs: 'https://raw.githubusercontent.com/iodr-blip/Nft_and_icons/main/Stickers/VooDooDall.tgs', color: 'c3' }
];

export const TON_ICON = "https://cryptologos.cc/logos/toncoin-ton-logo.svg?v=040";
